spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thogakade_db?createDatabaseIfNotExist=true
    username: root
    password: PasinduDev678

  flyway:
    enabled: true
    baseline-on-migrate: true