spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thogakade?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASS}

  flyway:
    enabled: true
    baseline-on-migrate: true